CREATE DATABASE MARATHONDB;

USE MARATHONDB;

SELECT * FROM MARATHON;

SELECT * FROM MARATHON 
ORDER BY FIRSTNAME;

SELECT * FROM MARATHON WHERE AGE> 40;
SELECT PACE 
FROM MARATHON 
WHERE AGE = AVG (40 AND 50)


SELECT FIRSTNAME,PLACE
FROM MARATHON 
WHERE STATE ='RI' AND
AGE>'40'
ORDER BY FIRSTNAME;

SELECT FIRSTNAME,LASTNAME
FROM MARATHON 
WHERE FIRSTNAME=N prov AND
LAST
ORDER BY FIRSTNAME

SELECT AGE 
FROM MARATHON 
WHERE MIN = AGE>39;
